name: Pull request checks

on: push

jobs:
  commit-message-check:
    name: Block fixup and squash commits

    runs-on: ubuntu-latest

    steps:
      - name: Run check
        uses: ./
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
